projects/urls.py
from django.urls import path
from . import views

app_name = 'projects'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:project_id>', views.detail, name='detail')
]

site_/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from . import views


app_name = 'home'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('projects/', include('projects.urls')),
    path('', views.home, name='index'),
]

projects/models.py
from django.db import models

class Projects(models.Model):
    name = models.CharField(max_length=255)
    info = models.CharField(max_length=1000, default='')
    image_url = models.CharField(max_length=255, default='') 
    github_url = models.CharField(max_length=255, default='')

    def __str__(self):
        return self.name

projects/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, Http404
from .models import Projects


def index(request):
    projects = Projects.objects.all()
    return render(request, 'projects/index.html', { 'projects': projects })

def detail(request, project_id):
    project = get_object_or_404(Projects, pk=project_id)
    return render(request, 'projects/detail.html', { 'project': project })
    

site_/views.py
from django.shortcuts import render
from projects.models import Projects

def home(request):
    projects = Projects.objects.all()
    return render(request, 'home.html', { 'projects': projects })

projects/templates/projects/detail.html
{% extends 'base.html' %}
{% block content %}
    <dl>
        <dt> {{ project.name }} </dt>
        <dd> {{ project.info }} </dd>
    </dl>
{% endblock  %}

projects/templates/projects/index.html
{% extends 'base.html' %}
{% block content %}
    <div class="row">
        {% for project in projects %}
            <div class="col">
                <div class="card" style="width: 18rem;">
                    <img src="{{ project.image_url }}" class="card-img-top" alt="...">
                    <div class="card-body">
                        <h5 class="card-title">{{ project.name }}</h5>
                        <p class="card-text"></p>
                        <a href={% url 'projects:detail' project.id %} class="btn btn-primary">info</a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock  %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{%  static  'styles.css'  %}" />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
      integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk"
      crossorigin="anonymous"
    />

    <title>Personal website</title>
  </head>

  <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top" >
    <button
      class="navbar-toggler"
      type="button"
      data-toggle="collapse"
      data-target="#navbarNav"
      aria-controls="navbarNav"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item active">
          <a class="nav-link" href="#"
            >Home<span class="sr-only">(current)</span></a
          >
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#projects">Projects</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#contact">Contact</a>
        </li>
      </ul>
    </div>
  </nav>

  <body>
    {% block content %} {% endblock %}</div>
    <section class='site_bottom' id="contact">
      <div class="container">
        <div class="row" style='padding-top: 50px; padding-bottom: 50px;'>
          <div class="col-sm" style="color: white; padding-bottom: 50px;">
            <h1>Contacts</h1>
          </div>
          <div class="col-sm" style="color: white;">
            <h3><a href="https://github.com/OneTrick475" target="blank">Github</a></h3>
            <h3>ibukev4@gmail.com</h3>
          </div>
        </div>
      </div>
    </section>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script
      src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
      integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
      integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
      integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

templates/home.html
{% extends 'base.html' %} {% block content %}

<section class="site-banner">
  <div class="site-banner-content">
    <h1 class="site-banner__title">
      Hey, I’m Ivan
      <h2 class="site-banner__subtitle">A programmer.</h2>
    </h1>
  </div>
</section>

<h1 style="padding-top: 30px; padding-left: 10px">Projects</h1>
<div
  class="container-fluid"
  id="projects"
  style="padding-top: 50px; padding-bottom: 50px"
>
  <div class="row row-cols-1 row-cols-md-6">
    {% for project in projects %}
    <div class="col mb-4">
      <div class="card text-white bg-dark mb-3" style="width: 18rem">
        <img
          src="{{ project.image_url }}"
          class="card-img-top"
          alt="..."
          ,
          style="height: 260px"
        />
        <div class="card-body">
          <h5 class="card-title">{{ project.name }}</h5>
          <p class="card-text">{{ project.info }}</p>
          <a href="{{ project.github_url }}" class="btn btn-primary" target="blank">Github</a>
        </div>
      </div>
    </div>
    {% endfor %}
  </div> 
</div>

{% endblock %}